### ISSUE TITLE
Multitasking

### ISSUE THREAD

**Issue by V10lator** [Pokes303/WUPDownloader#1]
This tool seems slower than it could be. Now I don't have my computer at hand but from a quick look at the sources it looks like everything is done in one thread. So it might be a good idea to at least make libcurl independent from the UI by moving the download into it's own thread. Then make the callback functions you feed to libcurl small functions who just pass the data from libcurl to global variables (these variables might need clever locking to be thread save but not lock the download thread for too long) and in the main (UI) thread fetch the variables to display what you need.

I could love to help you with that but my PC is defective and coding on a mobile phone is a PITA.

P.S. you have memory leaks in case of libcurl errors. Should I open a new bug report pin-pointing them or is this one-liner enough?

**Comment by Pokes303** [comment]
Yes, the GUI processes were slowing downloads, but at those times i didn't know how to use threads. Now it's fixed by creating an std::thread (Because creating an OSThread is harder and it can be messed up easily) and the GUI things are independent and limited. Thanks for your report!
