### ISSUE TITLE
WUPDownloader v1.1 freezing when generating ticket

### ISSUE THREAD

**Issue by troystram** [Pokes303/WUPDownloader#2]
Using the (Y) button to generate a ticket doesn't seem to be working, it froze on me two times in a row (I let it sit for 3+ hours the first time, only about an hour the second time).

I then tried generating the ticket though the download process (I had skipped doing that the first time) and that worked in a short period of time.  I think the Y button to generate a fake title id is not working correctly.

**Comment by Pokes303** [comment]
Yes, there was a bug in how the ticket's filename is calculated. Now it's fixed in 1.2
Thanks for the report!
