### ISSUE TITLE
!!! COPYRIGHT VIOLATION !!!

### ISSUE THREAD

**Issue by V10lator** [Pokes303/WUPDownloader#3]
You're using codes from the WUT examples but these codes are licensed under the terms of the GPLv2 (see https://github.com/devkitPro/wut/blob/master/LICENSE.md ). So you're currently breaking copyright of WUT!

A quick fix would be to change your license to GPLv2 (or v3), too.

**Comment by V10lator** [comment]
Forgot to add proof that you're using WUT copyrighted codes, so here you go:

- https://github.com/Pokes303/WUPDownloader/blob/master/src/input.cpp#L127
- https://github.com/devkitPro/wut/blob/master/samples/cmake/swkbd/main.cpp#L92

**Comment by V10lator** [comment]
I'm one of the copyright holders of WUT now so let's make this more clear: If you don't change the license till 07. March 2020 I'll take legal actions against WUPDownloader.

**Comment by Justsnoopy30** [comment]
Rule #3 of the internet: Don't be a jerk.

**Comment by V10lator** [comment]
@Justsnoopy30 This isn't about me being a jerk but me wanting to release NUSspli (see what the only fork of WUPDownloader is but realize that no codes have been published yet cause of this licensing issue) without getting in the same legal trap @Pokes303 is right now.

//EDIT: This is NUSspli: `64 files changed, 3877 insertions(+), 1689 deletions(-)`
![IMG_20200507_002226](https://user-images.githubusercontent.com/1312422/81234449-0c0c9000-8ff9-11ea-9fbe-991e4b8cc524.jpg)
